<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>$(CommonTargetFramework)</TargetFramework>
    <RootNamespace>WarHub.ArmouryModel.Source.Yaml.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\WarHub.ArmouryModel.Source.Yaml\WarHub.ArmouryModel.Source.Yaml.csproj" />
    <ProjectReference Include="..\..\src\WarHub.ArmouryModel.Source\WarHub.ArmouryModel.Source.csproj" />
  </ItemGroup>

</Project>
