//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace WarHub.Armoury.Model.BattleScribeXml {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    [System.Xml.Serialization.XmlRootAttribute("catalogue", Namespace="http://www.battlescribe.net/schema/catalogueSchema", IsNullable=false)]
    public partial class Catalogue : Datablob {
        
        private string gameSystemIdField;
        
        private string gameSystemRevisionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string gameSystemId {
            get {
                return this.gameSystemIdField;
            }
            set {
                this.gameSystemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string gameSystemRevision {
            get {
                return this.gameSystemRevisionField;
            }
            set {
                this.gameSystemRevisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GameSystem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Catalogue))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Datablob {
        
        private Profile[] profilesField;
        
        private Rule[] rulesField;
        
        private InfoLink[] infoLinksField;
        
        private CostType[] costTypesField;
        
        private ProfileType[] profileTypesField;
        
        private ForceEntry[] forceEntriesField;
        
        private SelectionEntry[] selectionEntriesField;
        
        private EntryLink[] entryLinksField;
        
        private SelectionEntry[] sharedSelectionEntriesField;
        
        private SelectionEntryGroup[] sharedSelectionEntryGroupsField;
        
        private Rule[] sharedRulesField;
        
        private Profile[] sharedProfilesField;
        
        private string idField;
        
        private string nameField;
        
        private string bookField;
        
        private string pageField;
        
        private string revisionField;
        
        private string battleScribeVersionField;
        
        private string authorNameField;
        
        private string authorContactField;
        
        private string authorUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("profile", IsNullable=false)]
        public Profile[] profiles {
            get {
                return this.profilesField;
            }
            set {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("rule", IsNullable=false)]
        public Rule[] rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("infoLink", IsNullable=false)]
        public InfoLink[] infoLinks {
            get {
                return this.infoLinksField;
            }
            set {
                this.infoLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("costType", IsNullable=false)]
        public CostType[] costTypes {
            get {
                return this.costTypesField;
            }
            set {
                this.costTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("profileType", IsNullable=false)]
        public ProfileType[] profileTypes {
            get {
                return this.profileTypesField;
            }
            set {
                this.profileTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("forceEntry", IsNullable=false)]
        public ForceEntry[] forceEntries {
            get {
                return this.forceEntriesField;
            }
            set {
                this.forceEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("selectionEntry", IsNullable=false)]
        public SelectionEntry[] selectionEntries {
            get {
                return this.selectionEntriesField;
            }
            set {
                this.selectionEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entryLink", IsNullable=false)]
        public EntryLink[] entryLinks {
            get {
                return this.entryLinksField;
            }
            set {
                this.entryLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("selectionEntry", IsNullable=false)]
        public SelectionEntry[] sharedSelectionEntries {
            get {
                return this.sharedSelectionEntriesField;
            }
            set {
                this.sharedSelectionEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("selectionEntryGroup", IsNullable=false)]
        public SelectionEntryGroup[] sharedSelectionEntryGroups {
            get {
                return this.sharedSelectionEntryGroupsField;
            }
            set {
                this.sharedSelectionEntryGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute("rule", IsNullable=false)]
        public Rule[] sharedRules {
            get {
                return this.sharedRulesField;
            }
            set {
                this.sharedRulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        [System.Xml.Serialization.XmlArrayItemAttribute("profile", IsNullable=false)]
        public Profile[] sharedProfiles {
            get {
                return this.sharedProfilesField;
            }
            set {
                this.sharedProfilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger")]
        public string revision {
            get {
                return this.revisionField;
            }
            set {
                this.revisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string battleScribeVersion {
            get {
                return this.battleScribeVersionField;
            }
            set {
                this.battleScribeVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authorName {
            get {
                return this.authorNameField;
            }
            set {
                this.authorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authorContact {
            get {
                return this.authorContactField;
            }
            set {
                this.authorContactField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string authorUrl {
            get {
                return this.authorUrlField;
            }
            set {
                this.authorUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Profile : EntryBase {
        
        private Characteristic[] characteristicsField;
        
        private string profileTypeIdField;
        
        private string profileTypeNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("characteristic", IsNullable=false)]
        public Characteristic[] characteristics {
            get {
                return this.characteristicsField;
            }
            set {
                this.characteristicsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileTypeId {
            get {
                return this.profileTypeIdField;
            }
            set {
                this.profileTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string profileTypeName {
            get {
                return this.profileTypeNameField;
            }
            set {
                this.profileTypeNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Characteristic {
        
        private string nameField;
        
        private string characteristicTypeIdField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string characteristicTypeId {
            get {
                return this.characteristicTypeIdField;
            }
            set {
                this.characteristicTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class CharacteristicType {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class ProfileType {
        
        private CharacteristicType[] characteristicTypesField;
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("characteristicType", IsNullable=false)]
        public CharacteristicType[] characteristicTypes {
            get {
                return this.characteristicTypesField;
            }
            set {
                this.characteristicTypesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class CostType {
        
        private string idField;
        
        private string nameField;
        
        private decimal defaultCostLimitField;
        
        public CostType() {
            this.defaultCostLimitField = ((decimal)(0.0m));
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal defaultCostLimit {
            get {
                return this.defaultCostLimitField;
            }
            set {
                this.defaultCostLimitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Cost {
        
        private string nameField;
        
        private string costTypeIdField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string costTypeId {
            get {
                return this.costTypeIdField;
            }
            set {
                this.costTypeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class ConditionGroup {
        
        private Condition[] conditionsField;
        
        private ConditionGroup[] conditionGroupsField;
        
        private ConditionGroupKind typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("condition", IsNullable=false)]
        public Condition[] conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("conditionGroup", IsNullable=false)]
        public ConditionGroup[] conditionGroups {
            get {
                return this.conditionGroupsField;
            }
            set {
                this.conditionGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConditionGroupKind type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Condition : SelectorBase {
        
        private string childIdField;
        
        private ConditionKind typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string childId {
            get {
                return this.childIdField;
            }
            set {
                this.childIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConditionKind type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public enum ConditionKind {
        
        /// <remarks/>
        lessThan,
        
        /// <remarks/>
        greaterThan,
        
        /// <remarks/>
        equalTo,
        
        /// <remarks/>
        notEqualTo,
        
        /// <remarks/>
        atLeast,
        
        /// <remarks/>
        atMost,
        
        /// <remarks/>
        instanceOf,
        
        /// <remarks/>
        notInstanceOf,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Condition))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Repeat))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Constraint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class SelectorBase {
        
        private string fieldField;
        
        private string scopeField;
        
        private decimal valueField;
        
        private bool percentValueField;
        
        private bool sharedField;
        
        private bool includeChildSelectionsField;
        
        private bool includeChildForcesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool percentValue {
            get {
                return this.percentValueField;
            }
            set {
                this.percentValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool shared {
            get {
                return this.sharedField;
            }
            set {
                this.sharedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool includeChildSelections {
            get {
                return this.includeChildSelectionsField;
            }
            set {
                this.includeChildSelectionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool includeChildForces {
            get {
                return this.includeChildForcesField;
            }
            set {
                this.includeChildForcesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Repeat : SelectorBase {
        
        private string childIdField;
        
        private string repeatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string childId {
            get {
                return this.childIdField;
            }
            set {
                this.childIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string repeats {
            get {
                return this.repeatsField;
            }
            set {
                this.repeatsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Constraint : SelectorBase {
        
        private string idField;
        
        private ConstraintKind typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ConstraintKind type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public enum ConstraintKind {
        
        /// <remarks/>
        min,
        
        /// <remarks/>
        max,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public enum ConditionGroupKind {
        
        /// <remarks/>
        and,
        
        /// <remarks/>
        or,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Modifier {
        
        private Repeat[] repeatsField;
        
        private Condition[] conditionsField;
        
        private ConditionGroup[] conditionGroupsField;
        
        private ModifierKind typeField;
        
        private string fieldField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("repeat", IsNullable=false)]
        public Repeat[] repeats {
            get {
                return this.repeatsField;
            }
            set {
                this.repeatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("condition", IsNullable=false)]
        public Condition[] conditions {
            get {
                return this.conditionsField;
            }
            set {
                this.conditionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("conditionGroup", IsNullable=false)]
        public ConditionGroup[] conditionGroups {
            get {
                return this.conditionGroupsField;
            }
            set {
                this.conditionGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ModifierKind type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public enum ModifierKind {
        
        /// <remarks/>
        set,
        
        /// <remarks/>
        increment,
        
        /// <remarks/>
        decrement,
        
        /// <remarks/>
        append,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntryLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectionEntryGroup))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectionEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ForceEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CategoryEntry))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InfoLink))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Rule))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Profile))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class EntryBase {
        
        private Profile[] profilesField;
        
        private Rule[] rulesField;
        
        private InfoLink[] infoLinksField;
        
        private Modifier[] modifiersField;
        
        private string idField;
        
        private string nameField;
        
        private string bookField;
        
        private string pageField;
        
        private bool hiddenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("profile", IsNullable=false)]
        public Profile[] profiles {
            get {
                return this.profilesField;
            }
            set {
                this.profilesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("rule", IsNullable=false)]
        public Rule[] rules {
            get {
                return this.rulesField;
            }
            set {
                this.rulesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("infoLink", IsNullable=false)]
        public InfoLink[] infoLinks {
            get {
                return this.infoLinksField;
            }
            set {
                this.infoLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("modifier", IsNullable=false)]
        public Modifier[] modifiers {
            get {
                return this.modifiersField;
            }
            set {
                this.modifiersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string book {
            get {
                return this.bookField;
            }
            set {
                this.bookField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string page {
            get {
                return this.pageField;
            }
            set {
                this.pageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool hidden {
            get {
                return this.hiddenField;
            }
            set {
                this.hiddenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class Rule : EntryBase {
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class InfoLink : EntryBase {
        
        private string targetIdField;
        
        private InfoLinkKind typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetId {
            get {
                return this.targetIdField;
            }
            set {
                this.targetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public InfoLinkKind type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public enum InfoLinkKind {
        
        /// <remarks/>
        profile,
        
        /// <remarks/>
        rule,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class EntryLink : EntryBase {
        
        private Constraint[] constraintsField;
        
        private string targetIdField;
        
        private EntryLinkKind typeField;
        
        private string categoryEntryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("constraint", IsNullable=false)]
        public Constraint[] constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string targetId {
            get {
                return this.targetIdField;
            }
            set {
                this.targetIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public EntryLinkKind type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string categoryEntryId {
            get {
                return this.categoryEntryIdField;
            }
            set {
                this.categoryEntryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public enum EntryLinkKind {
        
        /// <remarks/>
        selectionEntry,
        
        /// <remarks/>
        selectionEntryGroup,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class SelectionEntryGroup : EntryBase {
        
        private Constraint[] constraintsField;
        
        private SelectionEntry[] selectionEntriesField;
        
        private SelectionEntryGroup[] selectionEntryGroupsField;
        
        private EntryLink[] entryLinksField;
        
        private bool collectiveField;
        
        private string defaultSelectionEntryIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("constraint", IsNullable=false)]
        public Constraint[] constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("selectionEntry", IsNullable=false)]
        public SelectionEntry[] selectionEntries {
            get {
                return this.selectionEntriesField;
            }
            set {
                this.selectionEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("selectionEntryGroup", IsNullable=false)]
        public SelectionEntryGroup[] selectionEntryGroups {
            get {
                return this.selectionEntryGroupsField;
            }
            set {
                this.selectionEntryGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entryLink", IsNullable=false)]
        public EntryLink[] entryLinks {
            get {
                return this.entryLinksField;
            }
            set {
                this.entryLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool collective {
            get {
                return this.collectiveField;
            }
            set {
                this.collectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string defaultSelectionEntryId {
            get {
                return this.defaultSelectionEntryIdField;
            }
            set {
                this.defaultSelectionEntryIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class SelectionEntry : EntryBase {
        
        private Constraint[] constraintsField;
        
        private SelectionEntry[] selectionEntriesField;
        
        private SelectionEntryGroup[] selectionEntryGroupsField;
        
        private EntryLink[] entryLinksField;
        
        private Cost[] costsField;
        
        private bool collectiveField;
        
        private string categoryEntryIdField;
        
        private SelectionEntryKind typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("constraint", IsNullable=false)]
        public Constraint[] constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("selectionEntry", IsNullable=false)]
        public SelectionEntry[] selectionEntries {
            get {
                return this.selectionEntriesField;
            }
            set {
                this.selectionEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("selectionEntryGroup", IsNullable=false)]
        public SelectionEntryGroup[] selectionEntryGroups {
            get {
                return this.selectionEntryGroupsField;
            }
            set {
                this.selectionEntryGroupsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entryLink", IsNullable=false)]
        public EntryLink[] entryLinks {
            get {
                return this.entryLinksField;
            }
            set {
                this.entryLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("cost", IsNullable=false)]
        public Cost[] costs {
            get {
                return this.costsField;
            }
            set {
                this.costsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool collective {
            get {
                return this.collectiveField;
            }
            set {
                this.collectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string categoryEntryId {
            get {
                return this.categoryEntryIdField;
            }
            set {
                this.categoryEntryIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public SelectionEntryKind type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public enum SelectionEntryKind {
        
        /// <remarks/>
        upgrade,
        
        /// <remarks/>
        model,
        
        /// <remarks/>
        unit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class ForceEntry : EntryBase {
        
        private Constraint[] constraintsField;
        
        private CategoryEntry[] categoryEntriesField;
        
        private ForceEntry[] forceEntriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("constraint", IsNullable=false)]
        public Constraint[] constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("categoryEntry", IsNullable=false)]
        public CategoryEntry[] categoryEntries {
            get {
                return this.categoryEntriesField;
            }
            set {
                this.categoryEntriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("forceEntry", IsNullable=false)]
        public ForceEntry[] forceEntries {
            get {
                return this.forceEntriesField;
            }
            set {
                this.forceEntriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class CategoryEntry : EntryBase {
        
        private Constraint[] constraintsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("constraint", IsNullable=false)]
        public Constraint[] constraints {
            get {
                return this.constraintsField;
            }
            set {
                this.constraintsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.battlescribe.net/schema/catalogueSchema")]
    public partial class GameSystem : Datablob {
    }
}
