using System;
using System.Collections.Immutable;
using Microsoft.CodeAnalysis;

namespace WarHub.ArmouryModel.Concrete.Generators;

internal static class AttributeSources
{
    public const string GenerateSymbolAttributeName = "WarHub.ArmouryModel.Concrete.GenerateSymbolAttribute";
    public const string BoundAttributeName = "WarHub.ArmouryModel.Concrete.BoundAttribute";

    public const string GenerateSymbolAttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace WarHub.ArmouryModel.Concrete
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false)]
            [global::System.Diagnostics.Conditional("CONCRETE_EXTENSIONS_GENERATORS")]
            internal sealed class GenerateSymbolAttribute : global::System.Attribute
            {
                public GenerateSymbolAttribute(global::WarHub.ArmouryModel.SymbolKind kind)
                {
                    Kind = kind;
                }

                public global::WarHub.ArmouryModel.SymbolKind Kind { get; }
            }
        }
        """;

    public const string BoundAttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace WarHub.ArmouryModel.Concrete
        {
            [global::System.AttributeUsage(global::System.AttributeTargets.Property, Inherited = false)]
            [global::System.Diagnostics.Conditional("CONCRETE_EXTENSIONS_GENERATORS")]
            internal sealed class BoundAttribute : global::System.Attribute
            {
            }
        }
        """;
}
