using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace WarHub.ArmouryModel.Concrete.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class BoundGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("BoundAttribute.g.cs", AttributeSources.BoundAttributeSource);
        });

        var boundProperties = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeSources.BoundAttributeName,
            predicate: static (node, _) => node is PropertyDeclarationSyntax,
            transform: static (ctx, ct) => ExtractModel(ctx, ct))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value);

        // Collect all bound properties, then group by containing type
        var grouped = boundProperties.Collect().Select(static (items, ct) =>
        {
            var groups = new Dictionary<string, List<string>>();
            var typeInfos = new Dictionary<string, BoundTypeInfo>();
            foreach (var item in items)
            {
                ct.ThrowIfCancellationRequested();
                var key = item.FullTypeName;
                if (!groups.TryGetValue(key, out var list))
                {
                    list = new List<string>();
                    groups[key] = list;
                    typeInfos[key] = new BoundTypeInfo(item.Namespace, item.ClassName, item.IsSealed);
                }
                list.Add(item.PropertyName);
            }
            var result = ImmutableArray.CreateBuilder<BoundClassModel>(groups.Count);
            foreach (var kvp in groups)
            {
                ct.ThrowIfCancellationRequested();
                var info = typeInfos[kvp.Key];
                result.Add(new BoundClassModel(
                    info.Namespace,
                    info.ClassName,
                    kvp.Value.ToImmutableArray(),
                    info.IsSealed));
            }
            return result.ToImmutable();
        });

        context.RegisterSourceOutput(grouped, static (spc, models) =>
        {
            foreach (var model in models)
            {
                Execute(spc, model);
            }
        });
    }

    private static BoundPropertyModel? ExtractModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not IPropertySymbol propSymbol)
            return null;

        var containingType = propSymbol.ContainingType;
        if (containingType is null)
            return null;

        var ns = containingType.ContainingNamespace;
        var nsName = ns.IsGlobalNamespace ? null : ns.ToDisplayString();

        return new BoundPropertyModel(
            ns: nsName,
            className: containingType.Name,
            fullTypeName: containingType.ToDisplayString(),
            propertyName: propSymbol.Name,
            isSealed: containingType.IsSealed);
    }

    private static void Execute(SourceProductionContext spc, BoundClassModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName}");
        sb.AppendLine("{");

        // Use sealed override for sealed classes, plain override otherwise
        var modifiers = model.IsSealed ? "protected sealed override" : "protected override";
        sb.AppendLine($"    {modifiers} void CheckReferencesCore()");
        sb.AppendLine("    {");
        foreach (var prop in model.PropertyNames)
        {
            sb.AppendLine($"        _ = {prop};");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}.Bound.g.cs", sb.ToString());
    }

    private readonly struct BoundPropertyModel
    {
        public BoundPropertyModel(string? ns, string className, string fullTypeName, string propertyName, bool isSealed)
        {
            Namespace = ns;
            ClassName = className;
            FullTypeName = fullTypeName;
            PropertyName = propertyName;
            IsSealed = isSealed;
        }

        public string? Namespace { get; }
        public string ClassName { get; }
        public string FullTypeName { get; }
        public string PropertyName { get; }
        public bool IsSealed { get; }
    }

    private readonly struct BoundTypeInfo
    {
        public BoundTypeInfo(string? ns, string className, bool isSealed)
        {
            Namespace = ns;
            ClassName = className;
            IsSealed = isSealed;
        }

        public string? Namespace { get; }
        public string ClassName { get; }
        public bool IsSealed { get; }
    }

    private readonly struct BoundClassModel
    {
        public BoundClassModel(string? ns, string className, ImmutableArray<string> propertyNames, bool isSealed)
        {
            Namespace = ns;
            ClassName = className;
            PropertyNames = propertyNames;
            IsSealed = isSealed;
        }

        public string? Namespace { get; }
        public string ClassName { get; }
        public ImmutableArray<string> PropertyNames { get; }
        public bool IsSealed { get; }
    }
}
