using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace WarHub.ArmouryModel.Concrete.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class GenerateSymbolGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("GenerateSymbolAttribute.g.cs", AttributeSources.GenerateSymbolAttributeSource);
        });

        var symbolInfos = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeSources.GenerateSymbolAttributeName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, ct) => ExtractModel(ctx, ct))
            .Where(static x => x is not null);

        context.RegisterSourceOutput(symbolInfos, static (spc, model) => Execute(spc, model!.Value));
    }

    private static GenerateSymbolModel? ExtractModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var attr = ctx.Attributes[0];
        if (attr.ConstructorArguments.Length != 1 || attr.ConstructorArguments[0].Value is not int kindValue)
            return null;

        var kindName = attr.ConstructorArguments[0].Type?.GetMembers()
            .OfType<IFieldSymbol>()
            .FirstOrDefault(f => f.HasConstantValue && f.ConstantValue is int cv && cv == kindValue)
            ?.Name;

        if (kindName is null)
            return null;

        // Determine if the class inherits from Symbol (needs sealed override)
        // or just implements ISymbol (needs plain public)
        var inheritsSymbol = InheritsFromSymbol(typeSymbol);

        return new GenerateSymbolModel(
            ns: GetNamespace(typeSymbol),
            className: typeSymbol.Name,
            kindName: kindName,
            inheritsSymbol: inheritsSymbol,
            isSealed: typeSymbol.IsSealed);
    }

    private static bool InheritsFromSymbol(INamedTypeSymbol typeSymbol)
    {
        var current = typeSymbol.BaseType;
        while (current is not null)
        {
            if (current.Name == "Symbol" && current.ContainingNamespace.ToDisplayString() == "WarHub.ArmouryModel.Concrete")
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string? GetNamespace(INamedTypeSymbol symbol)
    {
        var ns = symbol.ContainingNamespace;
        return ns.IsGlobalNamespace ? null : ns.ToDisplayString();
    }

    private static void Execute(SourceProductionContext spc, GenerateSymbolModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {model.ClassName}");
        sb.AppendLine("{");

        if (model.InheritsSymbol)
        {
            // Regular symbol: sealed override for Kind and Accept
            sb.AppendLine($"    public sealed override global::WarHub.ArmouryModel.SymbolKind Kind => global::WarHub.ArmouryModel.SymbolKind.{model.KindName};");
            sb.AppendLine();
            sb.AppendLine($"    public sealed override void Accept(global::WarHub.ArmouryModel.SymbolVisitor visitor) =>");
            sb.AppendLine($"        visitor.Visit{model.KindName}(this);");
            sb.AppendLine();
            sb.AppendLine($"    public sealed override TResult Accept<TResult>(global::WarHub.ArmouryModel.SymbolVisitor<TResult> visitor) =>");
            sb.AppendLine($"        visitor.Visit{model.KindName}(this);");
            sb.AppendLine();
            sb.AppendLine($"    public sealed override TResult Accept<TArgument, TResult>(global::WarHub.ArmouryModel.SymbolVisitor<TArgument, TResult> visitor, TArgument argument) =>");
            sb.AppendLine($"        visitor.Visit{model.KindName}(this, argument);");
        }
        else
        {
            // Effective symbol: plain public methods (interface implementation)
            sb.AppendLine($"    public void Accept(global::WarHub.ArmouryModel.SymbolVisitor visitor) =>");
            sb.AppendLine($"        visitor.Visit{model.KindName}(this);");
            sb.AppendLine();
            sb.AppendLine($"    public TResult Accept<TResult>(global::WarHub.ArmouryModel.SymbolVisitor<TResult> visitor) =>");
            sb.AppendLine($"        visitor.Visit{model.KindName}(this);");
            sb.AppendLine();
            sb.AppendLine($"    public TResult Accept<TArgument, TResult>(global::WarHub.ArmouryModel.SymbolVisitor<TArgument, TResult> visitor, TArgument argument) =>");
            sb.AppendLine($"        visitor.Visit{model.KindName}(this, argument);");
        }

        sb.AppendLine("}");

        spc.AddSource($"{model.ClassName}.GenerateSymbol.g.cs", sb.ToString());
    }

    private readonly struct GenerateSymbolModel
    {
        public GenerateSymbolModel(string? ns, string className, string kindName, bool inheritsSymbol, bool isSealed)
        {
            Namespace = ns;
            ClassName = className;
            KindName = kindName;
            InheritsSymbol = inheritsSymbol;
            IsSealed = isSealed;
        }

        public string? Namespace { get; }
        public string ClassName { get; }
        public string KindName { get; }
        public bool InheritsSymbol { get; }
        public bool IsSealed { get; }
    }
}
