name: ChatOps
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: /command dispatch
        uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.SLASH_COMMAND_DISPATCH_TOKEN }}
          permission: maintain
          commands: deploy, tag
